version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: label
        must_include:
          regex: bug|documentation|enhancement|dependencies
          message: must include types
