[[repos]]
repo = "local"

[[repos.hooks]]
id = "gitleaks"
name = "gitleaks"
language = "system"
entry = "gitleaks protect --staged --redact"
pass_filenames = false

[[repos.hooks]]
id = "typos"
name = "typos"
language = "system"
entry = "typos"

[[repos.hooks]]
id = "zizmor"
name = "zizmor"
language = "system"
entry = "zizmor ."
pass_filenames = false
