name: Bump version (cron)

on:
  schedule:
    - cron: "15 3 * * TUE"

permissions:
  contents: write
  pull-requests: write

jobs:
  scheduled_bump:
    uses: ./.github/workflows/bump.yml
    secrets: inherit
    with:
      semver: minor
